dist: xenial
language: csharp
solution: Ubiety.Xmpp.Core.sln
mono: none
dotnet: 2.2.103
install:
  - dotnet tool install coveralls.net --tool-path tools
  - dotnet tool install coverlet.console --tool-path tools
  - sudo apt install wkhtmltopdf
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test
