branches:
  only:
    - master

skip_tags: true

image: Visual Studio 2017

dotnet_csproj:
  file: '**\*.csproj'

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  COVERALLS_REPO_TOKEN:
    secure: gw1sOtXvk1aiZZMJJQqBX5FXnjFt9F4IgtLLinQPqqAHpPg2NerYwX1XD9h5Kq3D

install:
  - ps: choco install wkhtmltopdf --no-progress -y
  - dotnet tool install --global coveralls.net
  - dotnet tool install --global coverlet.console

build_script:
  - dotnet restore
  - dotnet build

test_script:
  - coverlet Ubiety.Xmpp.Test/bin/Debug/netcoreapp2.1/Ubiety.Xmpp.Test.dll --target "dotnet" --targetargs "test Ubiety.Xmpp.Test/Ubiety.Xmpp.Test.csproj --no-build" --format opencover --exclude "[xunit.*]*"
  - csmacnz.Coveralls --opencover -i coverage.opencover.xml --useRelativePaths
