branches:
  only:
    - master
    - develop

skip_tags: true

image:
  - Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_API_KEY:
    secure: /Q19KwotffxsQLBeuWnovsx+inKCcn42o2BFrVC+X3VgofkJp5RdFVk+Ti1y0pF7
  COVERALLS_REPO_TOKEN:
    secure: gw1sOtXvk1aiZZMJJQqBX5FXnjFt9F4IgtLLinQPqqAHpPg2NerYwX1XD9h5Kq3D

build_script:
  - ps: .\build.ps1 --bootstrap --verbosity=diagnostic
  - ps: .\build.ps1 --currentBranch=$env:APPVEYOR_REPO_BRANCH --nugetKey=$env:NUGET_API_KEY --coverallsToken=$env:COVERALLS_REPO_TOKEN --verbosity=diagnostic

test: off
deploy: off
